# Generated by Django 3.2 on 2021-04-23 01:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_auto_20210422_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ['-created'], 'verbose_name': 'coach', 'verbose_name_plural': 'coaches'},
        ),
        migrations.RemoveField(
            model_name='coach',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='id',
        ),
        migrations.AddField(
            model_name='coach',
            name='coach_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='coach',
            name='email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coach',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('Tech Coach', 'Tech Coach'), ('Academic Coach', 'Academic Coach'), ('Talent Placement Coach', 'Talent Placement Coach')], max_length=100),
        ),
    ]
