# Generated by Django 3.2 on 2021-04-24 03:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0002_alter_coach_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('Talent Placement Coach', 'Talent Placement Coach'), ('Tech Coach', 'Tech Coach'), ('Academic Coach', 'Academic Coach')], max_length=100),
        ),
    ]
