# Generated by Django 3.2 on 2021-04-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaches', '0003_auto_20210423_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coach',
            name='role',
            field=models.CharField(choices=[('Tech Coach', 'Tech Coach'), ('Talent Placement Coach', 'Talent Placement Coach'), ('Academic Coach', 'Academic Coach')], max_length=100),
        ),
    ]
